.gitignore, .travis.yml, README.md, pytest.ini, requirements.txt
Addresses #4 
Note that #19 and #20 were uncovered as part of this.
=> Travis CI Integration

amazon/ion/core.py, amazon/ion/equivalence.py, amazon/ion/reader.py, amazon/ion/reader_binary.py, amazon/ion/reader_text.py, amazon/ion/simple_types.py, amazon/ion/simpleion.py, amazon/ion/util.py, amazon/ion/writer_binary_raw.py, amazon/ion/writer_text.py, tests/reader_util.py, tests/test_equivalence.py, tests/test_reader_base.py, tests/test_reader_binary.py, tests/test_reader_buffer.py, tests/test_reader_text.py, tests/test_simple_types.py, tests/test_simpleion.py, tests/test_vectors.py, tests/test_writer_binary_raw.py, tests/test_writer_text.py, tests/trampoline_util.py, tests/writer_util.py
Includes:
-simpleion text support
-equivalence module for comparing Python objects under the Ion data model
-test harness for ion-tests vectors
=> Adds non-blocking text reader.

amazon/ion/reader_text.py
This adds text reading support. It was already supported by the binary reader.
=> Adds support for the DEL (0x7f) character in clobs.

CHANGES.md, setup.py
And added change log, which should be updated at each future release.
=> Bumps version to 0.2.0.

CHANGES.md, setup.py
=> Bumps version to 0.3.0.

README.md
=> Puts simpleion front-and-center in the README.

tests/test_vectors.py
#74 
The decimal Emax and Emin limits are lower on 32-bit systems. They are even lower than the range of an `ssize_t`. Because the `subfieldVarInt.ion` test contains a decimal with a negative exponent that is less than the 32-bit Emin, this test must be skipped on 32-bit platforms.
=> Lowers the configured Emax and Emin in test_vectors into the platform-specific ranges.

MANIFEST.in
#72
(Replaces #76)
Results in the following output from `python setup.py sdist`:
```
running sdist
running egg_info
writing amazon.ion.egg-info/PKG-INFO
writing dependency_links to amazon.ion.egg-info/dependency_links.txt
writing namespace_packages to amazon.ion.egg-info/namespace_packages.txt
writing requirements to amazon.ion.egg-info/requires.txt
writing top-level names to amazon.ion.egg-info/top_level.txt
reading manifest file 'amazon.ion.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'amazon.ion.egg-info/SOURCES.txt'
running check
creating amazon.ion-0.3.1
creating amazon.ion-0.3.1/amazon
creating amazon.ion-0.3.1/amazon.ion.egg-info
creating amazon.ion-0.3.1/amazon/ion
creating …
```
=> Adds LICENSE, NOTICE, markdown files, tests source, and test vectors to the source distribution.

CHANGES.md, setup.py
In preparation for release 0.4.0.
=> Bumps version to 0.4.0 and updates CHANGES.md.

amazon/ion/simpleion.py, tests/test_simpleion.py
=> Adds support for `tuple` in `_FROM_TYPES` mapping.

CHANGES.md, setup.py
=> Bumps version to 0.4.1 and updates CHANGES.md

CHANGES.md, amazon/ion/__init__.py, setup.py
Version bump to `0.5.0`, update to CHANGES.md in anticipation of cutting the 0.5.0 release.
=> Version bump to 0.5.0, update to CHANGES.md.

tests/test_vectors.py
=> updates ion-test and skip list

CHANGES.md, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.6.0, updates CHANGES.md.

amazon/ion/encoder.py, amazon/ion/json_encoder.py, requirements.txt, tests/test_json_encoder.py
=> Add Ion-JSON encoder

CHANGES.md, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.7.0, updates CHANGES.md.

setup.py
=> adds jsonconversion to install_requires

C_EXTENSION.md
Added benefits of CodePipeline.
=> Updates document.

.github/workflows/main.yml
=> remove wrong lines.

.github/workflows/main.yml
=> Missing '.'

CHANGES.md, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.8.0.

C_EXTENSION.md, README.md
1. Removed 'beta'
2. updated URL for README.
3. Updated 'known issues' list.
=> update links, remove some solved issues.

CHANGES.md, MANIFEST.in, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.9.0.

CHANGES.md, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.9.1.

README.md
=> add installation guide in readme

.github/workflows/main.yml, .github/workflows/release.yml, install.py, requirements.txt, setup.py
=> Adds Github Actions for release automation.

CHANGES.md, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.9.2.

C_EXTENSION.md
=> Update C extension document.

CHANGES.md, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.9.3.

CHANGES.md, amazon/ion/__init__.py, setup.py, tests/test_benchmark_cli.py
=> Bumps version to 0.10.0.

CHANGES.md, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.11.0.

CHANGES.md, amazon/ion/__init__.py, setup.py
=> Bumps version to 0.11.2.

amazon/ion/ioncmodule.c
This change removes a strcpy to a temporary stack allocated array for
the field name of a Struct field. Instead it just allocates the
PyUnicode object for the field name, which does a copy anyway. The
copy is important because the ION_STRING is just a pointer to the
buffer which will change as we descend into parsing the Struct.
The performance impact of this change is measurable for some datasets
but not terribly significant. It is nonetheless an apparent simplifier
and therefore worth doing regardless.
** Please double check my DECREF-ing.**
=> Avoid strcpy of Field Names in C-Ext Read

.gitignore
n/a
Ignore generated temp files like:
* `temp_cat.10n`
* `temp_cat.ion`
* `temp_multiple_top_level_object.10n`
---
=> chore: ignore generated temp files

.github/dependabot.yml
None
This should help reduce some of the noise in our commit history while still keeping things up to date.
=> Update dependabot.yml schedule interval
