amazon/ion/simpleion.py
tests/test_simple_types.py

Previously the algorithm would fail given a subclass of any supported class

Ion type algorithm now inspects entire type hierarchy

---

setup.py

Using twine from the command line to upload the source distribution did -not- include the signature (.asc) file, and it cannot be added by itself either via the command line or the PyPI website. The "solution" is to do a post-release minor version bump to change the base file name of the release so that it doesn't conflict with the previous "dead" release. See also:
User complaints about PyPI's inability to re-upload identical files:
https://github.com/pypa/packaging-problems/issues/74
StackOverflow discussion of the same issue:
http://stackoverflow.com/questions/28708705/pypi-400-upload-error/28874414
Acceptable versioning schemes (with examples of .postX):
https://packaging.python.org/distributing/#choosing-a-versioning-scheme

Bumping to post-release version to get around PyPI upload error

---

amazon/ion/simpleion.py
tests/test_simpleion.py

I implemented `simpleion.dumps` as a simple wrapper over `simpleion.dump` using `six.BytesIO` as the file buffer.
I got an error when running existing tests:
tests/test_vectors.py:328: in <module>
_basic_params(_T.BAD, _BAD_UTF8_SUBDIR),
tests/test_vectors.py:199: in _basic_params
for file in _list_files(directory_path):
tests/test_vectors.py:174: in _list_files
for file in listdir(directory_path):
E   OSError: [Errno 2] No such file or directory: '/path/to/ion-python/vectors/iontestdata/good'
Does it have to do with my change or something I'm missing in my dev environment?
I hope contributions are accepted!

Adding an implementation of simpleion.dumps

---

amazon/ion/simpleion.py
tests/test_simpleion.py

Addresses #42 .
Adapts PR #57 to integrate with binary for `loads`/`dumps` and refactors the tests to work with `loads`/`dumps`.

Binary support loads() and dumps()

---

amazon/ion/writer_text.py
tests/test_simpleion.py
tests/test_writer_text.py
tests/writer_util.py

I didn't find a definitive list of keywords. I'm not sure if there are any others besides `null, nan, false, true`. I'd expect `inf` to be a keyword, but it worked out okay without quoting.
Found this: https://github.com/amzn/ion-python/blob/master/amazon/ion/reader_text.py#L1279-L1289

Escape textual ion symbols less often

---

.travis.yml
README.md
amazon/ion/util.py
tox.ini

#71 
[PEP 479](https://www.python.org/dev/peps/pep-0479/) makes an uncaught `StopIteration` within a generator function a `RuntimeError`. When StopIteration is expected within a generator, it may be caught at the source, allowing for a clean return. This change is forward- and backward-compatible.
Note: Travis CI [only supports](https://github.com/travis-ci/travis-ci/issues/9831) Python 3.7 on the Xenial distribution (with sudo enabled).

Adds support for Python 3.7.

---

tests/test_vectors.py

#74 
These limits were arbitrarily high. Setting them to the 32-bit max and min is fine, and should allow support for 32-bit platforms.

Lowers the configured Emax and Emin in test_vectors into the 32-bit range.

---

amazon/ion/core.py
amazon/ion/equivalence.py
amazon/ion/simple_types.py
amazon/ion/simpleion.py
tests/test_core_multimap.py
tests/test_simpleion.py
tests/test_vectors.py

Fixes: https://github.com/amzn/ion-python/issues/36

Keep all key-value pairs when the document has duplicate key names.

---

.travis.yml

* Python 2.6/3.3 are no longer supported so we should not support it.
* Also `dist: xenial` is now default for Travis CI, but we should be
explicit in our configuration to avoid breakage when the default changes.
Fixes #89

Sets Travis CI dist to Xenial and removes 2.6/2.7

---

.travis.yml
README.md
tox.ini

Updates tox.ini and README Python versions.
* Updates with current tip of versions.
* Removes no longer supported versions to match Travis config..
* Removes extraneous macOS specific commands.
* Fixes tox.ini to correspond to README.
* Minor clean up of Travis CI configuration (pypy3 has some issues
still).

Updates Tox/README Python Versions

---

amazon/ion/simple_types.py
tests/test_simple_types.py
tests/test_simpleion.py

This memoization was causing #95 because the `IonEvent.field_name` field
was being used when writing out struct fields instead of the key of the
field within the `IonPyDict`.  This meant that field with a value that
originated from another `IonPyDict` would retain field name from the original
`IonPyDict` when it was written out.

Remove memoization of events in _IonNature.

---

amazon/ion/__init__.py

This won't fix the current release, but sets this up so that our updated process for releasing ion-python will work normally.

Change self-reported version from 0.1.0 to 0.4.1

---

amazon/ion/simpleion.py
tests/test_simple_types.py
tests/test_simpleion.py

#96 
Before this change, the only way to write an s-expression using simpleion was first to construct an `IonPyList`, e.g.`IonPyList.from_value(IonType.SEXP, ('foo', 'bar'))`.
After this change, the user can simply enable the `tuple_as_sexp` option on `simpleion.dump` or `simpleion.dumps` to have tuples written directly to s-expressions without requiring an `IonPyList`. For example:
```
>>> dumps((123, u'abc', ({u'foo': ()}, )), binary=False, tuple_as_sexp=True)
'$ion_1_0 (123 "abc" ({foo:()}))'
>>> dumps((123, u'abc', ({u'foo': ()}, )), binary=False, tuple_as_sexp=False)
'$ion_1_0 [123,"abc",[{foo:[]}]]'
```

Adds the 'tuple_as_sexp' option to simpleion dump/dumps, giving the users the option to write tuples as Ion s-expressions.

---

amazon/ion/core.py
amazon/ion/reader_text.py

Continues #100 and #102 
Removes `_scale_to_precision` because it's a simple `Decimal.scaleb` and its bounds verification logic is unnecessary. Removes `_fractional_seconds_to_microseconds` because it's a one-liner used in one place and can be adequately explained with a line comment.

Simplifies caluculation of fractional seconds from an integer.

---

amazon/ion/core.py
amazon/ion/reader_text.py
amazon/ion/writer_text.py
tests/writer_util.py

Continues #100 
Creates a unified path for text serialization of timestamp fractional seconds regardless of how `str` would represent the Decimal. Reduces string manipulations.

Simplifies text writing of timestamps with Decimal fractional seconds.

---

amazon/ion/simple_types.py
amazon/ion/simpleion.py
tests/test_events.py
tests/test_simple_types.py

Resolves #104 
With these changes, cases in which IonEvent.field_name was a SymbolToken, but #97 changed to string, are once again SymbolTokens.

Compensates for #97's unintended changes to IonEvent.field_name behavior

---

amazon/ion/core.py
amazon/ion/reader_binary.py
amazon/ion/reader_text.py
amazon/ion/simple_types.py
amazon/ion/writer_binary_raw.py
amazon/ion/writer_text.py
tests/test_timestamp.py
tests/test_writer_binary_raw.py
tests/writer_util.py

Continues #100
* In the `Timestamp` docstring:
* Explicitly states that `fractional_seconds=Decimal(0)` is equivalent to having no precision past seconds. 
* Clarifies that under all circumstances, a constructed `Timestamp` will have populated values for `microsecond`, `fractional_precision`, and `fractional_seconds`.
* Makes the `Timestamp` constructor comply with the contract laid out in the docstring.
* Allows `microsecond` to be specified as either a positional or a keyword argument.
* Fixes the range checking for `fractional_precision` and `fractional_seconds` and the associated tests.
* Removes all defaulting logic from the `timestamp` function. In previous revisions this defaulting led to incongruity between results of `Timestamp` …

Makes the Timestamp constructor comply with the contract stated in its docstring; simplifies Timestamp writing logic where possible.

---

amazon/ion/simpleion.py
tests/test_simpleion.py

Adds option to omit the Ion version marker from text output

---

amazon/ion/simpleion.py

Updates logic just introduced by https://github.com/amzn/ion-python/pull/109.  The behavior is the same, but this is the correct logic.

Corrects condition logic around sending ION_VERSION_MARKER_EVENT to writer

---

amazon/ion/core.py

*Issue #, if available:* #124 
*Description of changes:* Using OrderedDict for STRUCT
I have executed `python setup.py test` and all 25895 tests passed. Are there any other tests that I need to run?

Using OrderedDict for STRUCT in IonPyDict or MultiMap

---

amazon/ion/simple_types.py
amazon/ion/util.py

I had the PR https://github.com/amzn/ion-python/pull/12 with the same purpose but this PR is having less change. So I closed the other one and opened this one. If still you think the other one was better, let me know.
*Issue #, if available:* https://github.com/amzn/ion-python/issues/126
The error message I was getting before this change was similar to https://github.com/amzn/ion-python/issues/61 so this MR may also resolve that issue. But I do not know and I have not tested it.
Because the `IonPyValueType` is defined in a function and not in the module scope so it is not picklable 
according to [python documentation](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled) and it seems `Enum` type was needing `__getnewargs__` function. I …

make IonPy* types picklable

---

README.md
tests/test_cookbook.py

Accompanies #10 and https://github.com/amzn/ion-docs/pull/118
Tests for the Python examples included in the cookbook (see https://github.com/amzn/ion-docs/pull/118).
Normally in Ion unit tests you wouldn't do three things that these tests do:
1. Compare against a canonical encoding, e.g. raw string comparisons to assert that text Ion data is correct. We break this rule in these tests in cases where the cookbook examples assert that a particular output will occur. If these tests fail, we will determine that the result is equivalent and then change both the test assertion *and* the cookbook example.
2. Have tests without any assertions. We break this rule in certain cases where the examples do not assert that a particular output will occur. …

Adds tests for the Python cookbook examples.

---

amazon/ion/reader_binary.py
amazon/ion/writer_binary_raw.py
tests/test_decimal.py

*Issue #132*
Use [`localcontext`](https://docs.python.org/3.7/library/decimal.html#decimal.localcontext) from to adjust the precision and allow any number of type `decimal` to be correctly de/serialized from/to Ion.
Also, I don't know where and how to add tests to prevent potential regression bugs. Locally I ran `python setup.py test` and all tests passed and in addition I used the following snippet:
```python
from decimal import Decimal
import amazon.ion.simpleion as ion
from hypothesis import given, example
from hypothesis.strategies import decimals
ion_decimals = decimals(allow_nan=False, allow_infinity=False)
@given(ion_decimals)
@example(Decimal('1005826281919371473355538432.5'))
def test_decimal(value):
recovered_value = Decimal(ion.loads(ion.dumps(value))) …
```

Fix: use localcontext to handle decimals of any precision

---

amazon/ion/simpleion.py

As mentioned in #137, this PR is trying to generate a detail error message for missing ion_type.
It would be easier to navigate the missing ion_type object by giving object value and its depth. In addition, if the object is inside a STRUCT, the `filed` will be the key instead of None.
&nbsp;
**1. Missing `ion_sym`'s ion_type** 
```.py
from amazon.ion import simpleion as ion
ion_sym = ion.IonPySymbol('SomeSymbol', None)
ion_bytes = ion.dumps(ion_sym, binary=True)
```
**Error message:**
```.py
amazon.ion.exceptions.IonException: ion_type 'None' is not allowed in value: "IonPySymbol(text='SomeSymbol', sid=None, location=None)", depth: 0, field: None
```
**2. Missing `ion_sym`'s ion_type (inside a struct)**
```.py
from amazon.ion import simpleion as ion
from collections import OrderedDict …
```

Issue 137, have a detail error message for missing ion_type.

---

amazon/ion/writer_binary.py
tests/test_simpleion.py

This PR worked on issue #140.
The binary writer doesn't include the case that field_name is an empty string.
&nbsp;
**Test code:**
```.py
from amazon.ion.simpleion import dumps
obj = {'': ''}
print(dumps(obj, binary=True))
```
**Output:** 
```
b'\xe0\x01\x00\xea\xe7\x81\x83\xde\x83\x87\xb1\x80\xde\x82\x8a\x80'
```
which is: `$ion    ion_symbol_table::{  symbols:[""]  }     {"" :  ""} `
&nbsp;
**Unit test**:

Added support of empty string field_name.

---

.travis.yml

Worked on issue #142.
From the [log](https://travis-ci.com/github/amzn/ion-python/jobs/487953370#L280), the default version of `setuptool` is out of date that has some compatible issue.
`pip install --upgrade setuptools` solves it.

Ttravis failed for pypi. (issue 142)

---

.travis.yml
MANIFEST.in
amazon/ion/_ioncmodule.h
amazon/ion/ioncmodule.c
amazon/ion/simpleion.py
install.py
setup.py
tests/test_cookbook.py
tests/test_simpleion.py
tests/test_vectors.py
tests/test_writer_text.py
tests/writer_util.py

PR of C extension.  (both coding and configuration parts).
Distribution part may be changed but I'll create a separate PRs for them as needed. 
I added comment for myself from the feedback last time. (e.g. not use force-python-impl, check c skip list etc.)
C extension consists of three parts: `simpleion dump/load`, `c extension (e.g. for mac it's ionc.so)` and `ion-c binaries`. We will go through each of them below. 
**Highlights:**
We add c extension information [here](https://github.com/amzn/ion-python/pull/149/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R26), setup.py will build c extension during the build process. we can also manually build extension by `python setup.py build_ext`.
&nbsp;
Then we look into `install.py` where we prepare ion-c binaries …

C extension (speeds up simpleion dump/load)

---

.gitmodules
amazon/ion/ioncmodule.c
install.py
setup.py
tests/test_simpleion.py
tests/test_writer_binary_raw.py
tests/writer_util.py

Issues fix and integration/config script (`install.py`) enhencement.
1. **Fixed an [unit test](https://github.com/amzn/ion-python/pull/149#discussion_r632052251) failure**. For value `$11::$12::$13`, before we hardcoded `\x0b\x0c` ($11::$12) for annotations since pure python LST always have annotation come first, now it may be `\x0c\x0d` ($12::$13) as it satisfied some conditions such as C extension is enabled.  (code [here](https://github.com/amzn/ion-python/pull/154/files#diff-1968bd0f275d56ac7b9b8993f7b267109d55812d8577e7581036c803734c9470R274))
2. **Improved `install.py`.** 
1. Uses submodule to install ion-c,
2. `setup.py` is the only entrance of the project no matter users **check out from Github**, **install by pip** or **our dev package the project for release**.
3. Separated …

Prepare work before release beta version.

---

amazon/ion/ioncmodule.c

Fixed couple memory leak issues.  The main things changed in this pull request are: **decrease the reference count for all the new reference.**
`tracemalloc` module.
before:
```
ion-python/amazon/ion/simpleion.py:476 (load): size=252 MiB (+84.0 MiB), count=4586413 (+1528599), average=58 B
ion-python/amazon/ion/simpleion.py:465 (dump): size=33.9 MiB (+11.3 MiB), count=934046 (+311338), average=38 B
```
now:
```
ion-python/amazon/ion/simpleion.py:476 (load): size=27.5 KiB (+0 B), count=586 (+0), average=48 B
ion-python/amazon/ion/simpleion.py:465 (dump): size=2757 B (+0 B), count=34 (+0), average=81 B  
```

Fixes memory leak issues.

---

amazon/ion/core.py
amazon/ion/ioncmodule.c
tests/writer_util.py

Solved #160 --- C extension supports 9 timestamp precision now. Since Python's datetime only supports microsecond precision so this change only affects ion [timestamp](https://github.com/amzn/ion-python/blob/d3ab7c0d12a76df9356b296981276480ec6a9f59/amazon/ion/core.py#L394).
**Code details:**
When reading a timestamp, if it has more than 6 precision, constructing an ion timestamp by passing [fractional_seconds](https://github.com/amzn/ion-python/blob/d3ab7c0d12a76df9356b296981276480ec6a9f59/amazon/ion/core.py#L411) argument and otherwise using microseconds as before.
When writing a timestamp to a file. Reading at most 9 decimal digits that from python ion timestamp into C decQuad and using ion-c API to dump them.
✅ &nbsp;**Memory leak test**: No leak.
✅ &nbsp;**Performance measurement**: …

C extension supports 9 timestamp precision.

---

amazon/ion/ioncmodule.c

This PR is working on https://github.com/amzn/ion-python/issues/165 on ion-python layer and the fix of C layer is [here](https://github.com/amzn/ion-c/pull/260).
Configure reader/writer max annotation count to read/write more annotations.
This change passes ion-c tests, ion-python tests and ion-hash-python tests.

Fixes C extension can't write/read too much annotations issue.

---

.gitignore
amazon/ion/core.py
amazon/ion/ioncmodule.c
amazon/ion/simple_types.py
amazon/ion/simpleion.py
tests/test_simpleion.py

*Issue #, if available:* N/A
*Description of changes:* Converted the ionc_read implementation to return and iterator instance to allow processing large ION streams without having to load entire input buffers into memory. 
Sharing this pull request to see if there's interest to see these changes merged. If so, I can work on few improvements to this changeset to add more integration tests and verify there are no memory leak with valgrind etc..
*Testing:* Tested with unit test and made sure they all pass. And used this version briefly in a separate workload to process some big files.

Update simpleion.load function to support iterating infinite streams

---

.github/workflows/main.yml
requirements.txt

By our setup logic, we install the latest setuptool which 60.6.0 has an incompatible issue. Using 60.5.0 for now.
Refer to https://github.com/amzn/ion-python/issues/191 for details.

Fixes a setuptool version issue to setup the package during CI/CD successfully.

---

setup.py

fix #196
Adds install requires to setup.py according to the documentation: https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#install-requires

fix missing dependency

---

setup.py

**Description:**
Some C compilers complain that initializing variables within a for loop is invalid, move it outside.
**Test:**
see GHA below.

Initializes variables outside of the for loop.

---

C_EXTENSION.md

Linked an Ion Clob issue #207 to the document.

Updates document to link a Clob limitation issue.

---

amazon/ion/ioncmodule.c

`PyObject_HasAttrString(obj, "precision")` returns `True` even though the precision field is `None`.
Adds one more check to make sure wether a timestamp has a precision. 

Fixes a timestamp precision check issue.

---

amazon/ion/ioncmodule.c
tests/test_simpleion.py

This PR fixes https://github.com/amzn/ion-python/issues/213 and https://github.com/amzn/ion-python/issues/205
The root is because of unicode and UTF-8 conversion. 
For example, when we read a String IO including value `\u2013` by `fp.read(1)`, It will be converted to 3 bytes instead 1 later.
which failed [memory bounds check](https://github.com/amzn/ion-python/blob/master/amazon/ion/ioncmodule.c#L1429-L1432). 
Unicode detail, see https://www.fileformat.info/info/unicode/char/2013/index.htm
To avoid this, we maintain a 1024x32 bytes buffer, and only read 1024*32/4 bytes each time (since one code point can be up to 4 UTF-8 bytes)
The performance depends on the size of files we are going to read. On the one hand, if the file is really small but we maintain a large buffer, it’s not efficient …

Adjests read buffer size to avoid unicode/utf-8 conversion issue.

---

.github/workflows/main.yml
README.md
setup.py
tox.ini

This change move the oldest supported version of Python to 3.7.
Python 3.6 is now a year past EOL and is no longer supported on the
ubuntu images used for github builds.
This also bumps the *minor* version number. While there are no current
changes that _shouldn't_ work on 3.6, future changes may not.

Remove Python 3.6 from Builds, Bump Minor Version

---

amazon/ion/ioncmodule.c

Drop the support of python 2 in C extension.  
One thing need need to be done in this PR is benchmarking utcoffset calculation, details see [comment](https://github.com/amzn/ion-python/blob/master/amazon/ion/ioncmodule.c#L145-L146). 

Drop python 2 support in C extension.

---

tests/test_vectors.py

Two test files failed CI/CD with `pypy`, adds them to skip list.
#229 it's a known python security limitation that doesn't allow str<>decimal conversation for more than 4000~ digits. For issue #230 need more investigation. 
https://github.com/amazon-ion/ion-python/issues/229  - subfieldVarInt.ion
https://github.com/amazon-ion/ion-python/issues/230 - ivmInAnnotationWrapper.10n

Adds two tests to the skip list for pypy compatible.

---

amazon/ionbenchmark/API.py
amazon/ionbenchmark/Format.py
amazon/ionbenchmark/ion_benchmark_cli.py
tests/test_benchmark_cli.py

This PR adds support for multi-options execution - https://github.com/amazon-ion/ion-python/issues/226. 
For example, user provides `--api simple_ion`, `--api event`, `--format ion_text` and `--format ion_binary`. the CLI tool will generates combinations of all these two options (`--api` and `--format`) and execute each of them. 
E.g. the report should be something like 
|options|result|
|---|---|
|`--api simple_ion`,`--format ion_binary` |15s|
|`--api simple_ion`,`--format ion_text`|12s|
|`--api event`,`--format ion_binary`|15s|
|`--api event`,`--format ion_text`|11s|
In addition, this PR fixed few typo, modified unit test. I also left comments to highlight some changes.
Unit test, 204/204 passed
**Command**
```
(venv) ion-python % python amazon/ionbenchmark/ion_benchmark_cli.py write …
```

Adds support for multi-options execution.

---

amazon/ion/ioncmodule.c
amazon/ion/simpleion.py
tests/test_simpleion.py

This PR fixed https://github.com/amazon-ion/ion-python/issues/232
In short, ion-c's [symbol_threshold](https://github.com/amazon-ion/ion-c/blob/master/ionc/include/ionc/ion_reader.h#L101-L104) limited the size of the string we are able to read.
The exception is threw by [this line](https://github.com/amazon-ion/ion-c/blob/master/ionc/ion_reader_text.c#L1800). The reason that `eos_encountered` is false is because ion_scanner’s value buffer contains limited buffer, which is initialized [here](https://github.com/amazon-ion/ion-c/blob/master/ionc/ion_scanner.c#L93). You will see that value_buffer_length is assigned as symbol_threshold (512 bytes by default). 
So change the [option.symbol_threshold](https://github.com/amazon-ion/ion-c/blob/master/ionc/include/ionc/ion_reader.h#L101-L104) to a …

Adds support for flexible symbol buffer threshold.

---

.github/workflows/release.yml

We dropped 3.6 and pypy-3.6 support earlier, remove them from release script too.

Updates release versions

---

install.py

Using ion-c 1.1.0 specifically for ion-python to mitigate the issue https://github.com/amazon-ion/ion-python/issues/249.

Uses specific ion-c version to build ion-python.

---

amazon/ion/util.py
tests/test_util_enum.py

* Adds its meta class back without using six.
* Adds unit tests back
* Marks it as deprecation. Adds deprecation warnings for the class.
https://github.com/amazon-ion/ion-python/issues/241

Adds the simpleEnum class back.

---

amazon/ionbenchmark/API.py
amazon/ionbenchmark/Command.py
amazon/ionbenchmark/Format.py
amazon/ionbenchmark/Io_type.py
amazon/ionbenchmark/ion_benchmark_cli.py
install.py
requirements.txt
tests/benchmark_sample_data/cbor/sample
tests/benchmark_sample_data/json/object.json
tests/test_benchmark_cli.py

This PR integrates JSON/CBOR into the benchmark CLI. It additionally adds an IO type option to decide which IO type of the Ion data will be benchmarked. 
In details, this PR adds below features/components
1. Enable the CLI tool to benchmark Ion data as well as modern JSON/CBOR libraries concurrently.
2. Adds an IO type option to allow the tool benchmark time for either read/write in-memory buffers or files.
3. A bunch of refactor and unit testing.
Benchmark load API for all JSON libraries as well as ION
**Command and Output:**
```
python amazon/ionbenchmark/ion_benchmark_cli.py read --format json --format orjson --format simplejson --format ion_text --format ion_binary --format ujson
```
Benchmark dumps API (--io-types buffer) for CBOR2,  and Ion_binary
**Command and Output:**
```
python …
```

Adds JSON/CBOR support and an Io-type option

---

amazon/ion/core.py

This change fixes a bug where the empty Ion Struct was being
represented with only a closing brace.
After change:
```
>>> simpleion.loads('{}')
{}
>>> simpleion.loads('{"a":1}')
{'a': 1}
```
gh issue: https://github.com/amazon-ion/ion-python/issues/257

Fix __repr__ of Empty Struct

---

amazon/ion/simple_types.py
tests/test_equivalence.py

This change defines IonPyBool as it's own sub-class of int instead of
as an alias of IonPyInt.
Doing so removes the potential confusion around the python type and
__repr__ which could make Ion Booleans appear as Ion Ints.
gh issue: https://github.com/amazon-ion/ion-python/issues/88
After the change:
```
>>> from amazon.ion import simpleion
>>> b = simpleion.loads('true')
>>> b
True
>>> type(b)
<class 'amazon.ion.simple_types.IonPyBool'>
>>> b.ion_type
<IonType.BOOL: 1>
```

Define IonPyBool as Distinct Type

---

amazon/ion/simpleion.py

*Issue #, if available:* https://github.com/amazon-ion/ion-python/issues/251
*Description of changes:* Remember current file position then seek back to it after reading the IVM instead of blindly seeking to position 0.

fix: seek to previous position instead of 0 after reading IVM

---

requirements.txt

N/A
This PR updates the version of `setuptools` to `65.5.1` or later to resolve the[ Dependabot alert ](https://github.com/amazon-ion/ion-python/security/dependabot/2).
> Python Packaging Authority (PyPA)'s setuptools is a library designed to facilitate packaging Python projects. Setuptools version 65.5.0 and earlier could allow remote attackers to cause a denial of service by fetching malicious HTML from a PyPI package or custom PackageIndex page due to a vulnerable Regular Expression in package_index. This has been patched in version 65.5.1.

Update the version of setuptools to 65.5.1 or later

---

amazon/ion/core.py
amazon/ion/reader_binary.py
amazon/ion/reader_managed.py
amazon/ion/reader_text.py
amazon/ion/symbols.py
amazon/ion/util.py
amazon/ion/writer_binary.py
tests/reader_util.py
tests/test_core_iontype.py
tests/test_core_multimap.py
tests/test_reader_base.py
tests/test_reader_buffer.py
tests/test_reader_managed.py
tests/test_simple_types.py
tests/test_simpleion.py
tests/test_symbols_catalog.py
tests/test_symbols_table.py
tests/test_timestamp.py
tests/test_util_unicode.py
tests/test_writer_text.py
tests/trampoline_util.py
tests/writer_util.py

This change replaces all of the usages of the record super-type
constructor with the built-in NamedTuple. This makes the code easier
to read (no custom special type mojo) and enables IDEs and other tooling
to provide type hints when constructing and field name completion when
using instances.
The types which extend NamedTuple are immutable as they were before.
I'm sure there was a reason record was created initially, but I don't
see a good reason to keep it now, particularly given the benefits of
just using NamedTuple.
I kept the record constructor and metaclass to avoid breaking a
consumer who is using them. We can remove them when we release an MV.
By submitting this pull request, I confirm that my contribution is made under the terms …

Replace Usages of record with NamedTuple

---

amazon/ion/core.py
amazon/ion/reader_binary.py
amazon/ion/sliceable_buffer.py
tests/test_reader_binary.py
tests/test_sliceable_buffer.py

This commit refactors the pure python (non-extension) binary reader to
improve performance. My testing shows it to be roughly 2.5x faster.
It ditches the coroutine dispatching overhead within the reader and
replaces the stateful buffer with an immutable buffer that uses
memoryviews to decrease memory allocations. The immutability of the
buffer is less important for the binary reader but will be important
for the text reader where we often need to look ahead.
It contains a change to the IonThunkEvent that should have a positive
impact on the text reader as well. More impactful will be to apply
this pattern to the text reader.
I left the managed_reader unchanged though de-coroutining that and
minimizing managed event construction could yield more gains for both
text and binary.
*Issue #, if …

Binary Reader Performance Refactor

---

amazon/ionbenchmark/proto.py

**Issue #, if available:**
None
**Description of changes:**
Adds a module that provides functionality to make it easier to support standard protocol buffers in the benchmark CLI. Functionality includes:
* Wrapper for a protocol buffer `Message` that provides `load`/`loads` and `dump`/`dumps` for that message type
* Function to dynamically load a protocol buffer `Message` from a python module at runtime
* Function to dynamically generate a protocol buffer `Message` from a proto file descriptor at runtime
The functions for loading the `Message` are important because we can't hard-code the `Message` implementation into the benchmark CLI (since it's not necessarily known at compile time), so we need some way to load them at runtime.
_By submitting this pull request, I confirm that my …

Add module to load/dump standard protocol buffers

---

amazon/ion/simpleion.py
amazon/ionbenchmark/ion_benchmark_cli.py

In looking into why the pypy profiling was behaving erratically on GH
I observed that memory usage for the Ion Text tests in pure-python
mode was quite high: roughly 3gb for less than 500 iterations.
pypy uses the pure-python implementation.
In looking at the code I observed that setup_with_gc was not actually
being setup _with_ gc. Enabling it in these places makes a substantial
difference in memory use on my laptop.

Enable GC For Repeated Runs

---

.github/workflows/performance-regression.yml

This change factors some boilerplate out of the cli invocations.
It also lowers the warmups to 100 and run to 1000 because the runs
are taking very long and don't seem reliable even at the current levels.

Minor cleanups to Perf Regression Workflow YAML

---

amazon/ion/simpleion.py
tests/test_simpleion.py

**Issue #, if available:**
None.
**Description of changes:**
The `simpleion` module now keeps track of whether the c extension is loaded independently of the user-mutable `c_ext` flag. When determining whether to use the c extension, it checks both the user-mutable `c_ext` flag and the private `__IS_C_EXTENSION_SUPPORTED` flag.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

Fix c_ext flag so that users cannot enable the c extension when it is not loaded

---

amazon/ion/simple_types.py

IonPyDict's `add_item` is called recursively many times for Ion data that includes IonPyDict. This pull request introduces a 4-5% performance improvement by eliminating overhead caused by unnecessary method calls. 
I attempted to rewrite the C extension part as well to insert key-value pairs into the dictionary directly instead of calling `add_item` (see code [line 210-214](https://github.com/amazon-ion/ion-python/blob/master/amazon/ion/ioncmodule.c#L204-L214)), but I found that it was even slower than invoking the method directly.
Additionally, we are using OrderedDict to store key-value pairs which cannot use the raw CPython Dict API such as `PyDict_SetItem` to insert values.
It shows a 4-5% improvement for the sample file we are using. However, for specific use cases such as a large …

Avoids unnecessary method invocations in IonPyDict's add_item method.

---

.github/workflows/release.yml
CHANGES.md
README.md
amazon/ion/__init__.py
setup.py

Release workflow failed due to below error. This is because python 3.7 doesn't support this module. So in this PR, we bumps the version to 0.11.1 and drop the support of python versions <3.7.
```
tests/test_benchmark_cli.py:9: in <module>
from amazon.ionbenchmark.ion_benchmark_cli import TOOL_VERSION
amazon/ionbenchmark/ion_benchmark_cli.py:39: in <module>
from amazon.ionbenchmark.benchmark_runner import run_benchmark
amazon/ionbenchmark/benchmark_runner.py:13: in <module>
from amazon.ionbenchmark.sample_dist import SampleDist
amazon/ionbenchmark/sample_dist.py:7: in <module>
_unit_normal = statistics.NormalDist()
E   AttributeError: module 'statistics' has no attribute 'NormalDist'
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Bumps version to 0.11.1 and drops the support of Python versions older than 3.7.

---

.github/workflows/performance-regression.yml
amazon/ion/ioncmodule.c

*Issue #, if available:* #159
This PR fixes the issue identified in #159 where no more than 34 digits were supported in ion decimals.
There were 2 issues in this PR that should be made aware for anyone working with ion-c and decNumber.
Originally, ion-python's C extension initialized the `decContext` used for configuring the decNumber library with one of the available presets, `DEC_INIT_DECQUAD`. This preset configures the library with the expectation that you'll be using `decQuad`s, which are limited to 128bit, or 34 decimal digits. This configuration lead to ion-c returning `IERR_NUMERIC_OVERFLOW` when trying to load a larger than 34 digit decimal:
```
>> import amazon.ion.simpleion as ion
>>> ion.loads("9999999999999999999999999999999999999999999999999999999999 …
```

Add support for large decimals with >34 digits.

---

amazon/ion/simpleion.py

Some customers found that the lack of documentation makes them really hard to onboard Ion. While discussing and documenting a long-term solution, I'll use this PR to add common examples for the simpleion load/dump APIs first.

Adds common examples for the simpleion load/dump APIs.

---

amazon/ion/ioncmodule.c
amazon/ion/simple_types.py
tests/test_events.py
tests/test_simpleion.py

This PR is working on fixing https://github.com/amazon-ion/ion-python/issues/297. Users use the constructor and `from_value` method to construct Ion values. After the deprecation of IonNature, the constructor of IonPyObjects now have a `from_value`-like signature.
there are a few concerns we have, we need to
In this PR, I allowed both (1) Users should be able to use `from_value` method to construct Ion values.
(2) Users should be able to use IonPyObjects' constructor to construct Ion values, where it's inherited from their parent class (E.g., most of them are native python class such as Int, string)
However, to minimize the risk of breaking existing usage, the C extension return value constructions fall back to using `from_value` method so that IonValues constructions can reuse the …

Changes IonPyObjects' constructor to be same as their parents' classes.

---

install.py

This PR reverted https://github.com/amazon-ion/ion-python/pull/250 since the issue #249 is solved. 
In details, we do not use a specific ion-c version (v1.1.0) to build C extension anymore. 

Uses the latest ion-c version to build C extension

---

amazon/ion/simpleion.py

Before this change an ImportError other than ModuleNotFound would
cause an exception to propagate on import that prevented users
from using simpleion at all.
I've seen reports of two different users encountering this error
for two different reasons, and am confident this would fix both.
closes https://github.com/amazon-ion/ion-python/issues/300

Warn on ImportError when importing ionc

---

amazon/ion/ioncmodule.c
amazon/ion/simpleion.py
tests/test_simpleion.py

This change makes it so that the emit_bare_values flag to the
load_extension() method actually works. It does not plumb the
flag up to the user APIs.
Specifically:
* Bare Decimals are correctly emitted instead of tuples
* Values within a non-bare Sexp may now be bare themselves
* None is correctly Increffed when emitted as a bare value
I also patched a leak with ION_DECIMALs where the read decimal
was not being freed.
**PR Note:**
I'd like to see us expand what we emit as std python values, as I think
it will yield solid performance gains and I don't think most folks will 
miss the "ion-ness". But... "most" is not "all" so I think we will need a
set of flags to allow users to specify where they sacrifice fidelity for
speed and convenience.
By submitting this pull request, I confirm that …

Fix Bugs with emit_bare_values

---

amazon/ion/ioncmodule.c

This change simplifies the conversion of an ION_DECIMAL to a Python
Decimal when reading Decimals. Instead of converting the ION_DECIMAL
to a tuple of (sign, (digit, ...), exponent) it just gets the string
representation and uses the corresponding Decimal constructor.
This turns out to be about 20% faster for marshalling "bare value"
decimals of reasonable size (think amounts of money) and uses less
memory.
I also removed an unnecessary extra byte padding for int conversion,
removed a superfluous error check and clarified with comments.

Simplify ION_DECIMAL to Python Decimal Conversion

---

amazon/ion/simpleion.py

This change puts the user API methods at the top of the file
and moves the pydoc to the actual API methods. I followed the std
json module in the choice to put the main doc strings on dump and
load and have dumps and loads refer to them.
It also factors out the tables that were in loads and dumps into
a single table. I found the previous factoring very difficult to grok
and I believe this is more readable.
I also removed all of the unused kwarg parameters and their pydoc
strings. It added a lot of cognitive load for no value.
Finally I made some minor cleanings to Arg descs and corrected the
default text buffer value for loading with the C-Extension.
**Note to Reviewers:**
I've found the organization of the file, the conversion tables and the
unused args confusing for some time. As I …

Reorder simpleion and Refactor Pydoc

---

amazon/ion/ioncmodule.c
amazon/ionbenchmark/benchmark_spec.py
tests/test_simpleion.py

This change makes it so that Symbols are emitted as Symbol Tokens when
`emit_bare_values` is true. This gets most of the associated
performance gains for Symbols while still avoiding any type ambiguity
between Symbols and Strings.
Since IonPySymbol inherits from SymbolToken users may still check if
and act on a value being a Symbol with a single type check regardless
of "bare-ness." I changed the benchmark spec because it broke in my
own testing.
The flag is still not exposed to users so it shouldn't change anyone's
experience.

Emit SymbolTokens for Symbol "bare values"

---

amazon/ion/ioncmodule.c

N/A
In this PR, we have eliminated the `PyObject_HasAttrString` condition check because the `PyObject_GetAttrString` function  itself checks whether the attribute exists and will return NULL if it doesn't. If the `PyObject_GetAttrString` returns `NULL`, this indicates that an error has occurred, and we will handle the `AttributeError` under this condition.
Here is the benchmark results from benchmarking ion-python (C extension enabled) using shorthand log data.
There is 21.23% performance improvement (`time_mean`) on shorthand log data and 3.35% performance improvement(`time_mean`) on single nested test data.
**`ion-python-benchmark-cli` usage pattern to reproduce the benchmark results:**
` python ion_benchmark_cli.py write --iterations …

Remove PyObject_HasAttrString condition check.

---

amazon/ion/ioncmodule.c

This change makes it so that we try to read Ion INTs as int64s and
convert them to Python with PyLong_FromLongLong. If the int is too
large then we fallback to converting via base 10 string repr.
I don't like adding complexity but this is significantly faster for
datasets with small ints. For example, the "service_log_legacy"
benchmark is about 7% faster with this change.
**Note for Reviewers:**
I looked at other options for efficiently creating PyLongs (all Python
ints are actually "Longs" in Python 3) from Ion INTs. The highest 
"bandwith" way to do arbitrary size ints is getting them as two's 
complement byte arrays. Unfortunately there is no Python C API
call for that, so you need to go through the Object Call protocol
which adds a lot of overhead. There is no existing hex or base 32 …

Try to read and convert Ion INT as int 64

---

amazon/ion/ioncmodule.c

N/A
The updated method `ionc_write_big_int` initially attempts to convert the Python object to a C` long long` using `PyLong_AsLongLongAndOverflow`.  If the integer fits within a 64-bit range and no error occurs, it proceeds to write the integer directly using `ion_writer_write_int64`. For integers larger than 64-bit, it will fallback to string conversion. This PR also replaced method `PyObject_CallMethod(obj, "__str__", NULL)` with `PyObject_Str(obj)`, this also improve the performance. 
Here are the benchmark results from benchmarking ion-python writing using service_log_legacy: There is **_14.74%_** performance improvement from the change.
|                                      |   file_size(B) |   time_min(ns) |   time_mean(ns) | …

Enhance ionc_write_big_int method for optimized handling of large integers.

---

amazon/ion/ioncmodule.c

N/A
This PR introduces caching for the attribute names` ion_type` and `ion_annotations`. The motivation for this change comes from the [implementation ](https://github.com/python/cpython/blob/1ff02385944924db7e683a607da2882462594764/Objects/object.c#L1016) of `PyObject_GetAttrString()`, which includes a step to convert a C-style string to a Python string. To bypass this conversion process for frequently accessed attribute names like ` ion_type` and `ion_annotations`, we now cache these attribute names. In this case, we can use `PyObject_GetAttr()` directly for attribute access, enhancing overall efficiency.
Here are the benchmark results from benchmarking ion-python writing using service_log_legacy: 
There is _**21.64%**_ performance …

Cache the attribute name that is accessed repeatedly.

---

amazon/ion/_ioncmodule.h
amazon/ion/ioncmodule.c
amazon/ion/simpleion.py
tests/test_simpleion.py

This change adds an IonPyValueModel IntEnum to allow users to control
how Ion values map to IonPy and/or standard Python types when reading.
As noted previously, emitting "bare" values is significantly faster
than emitting IonPy values. I also added flags to affect how Symbols
and Structs map, though they are not yet supported. Profiling revealed
that using Python std types for these two had the most impact on perf,
aside from Timestamps which we are tackling independently.
My plan is to make these two flags work in the c-extension, evaluate
and go from there.
**Reviewer's Note:**
I put this into CR as-is to get some feedback on the naming and semantics
of the flags. I don't intend to merge any flags exposed to the user that aren't 
implemented, at least in the c-extension.
By submitting …

Added and Plumbed IonPyValueModel Flags

---

amazon/ion/ioncmodule.c
tests/test_simpleion.py

By default the IonPy value for a Symbol is IonPySymbol and the bare
value is a SymbolToken. With the SYMBOL_AS_TEXT flag set, the IonPy
value for a Symbol is IonPyText, and the bare value is str.
This makes Symbol handling simpler if one only cares about the text
value. It also improves load performance for symbols significantly.
Symbols with undefined text cannot be emitted with this flag set and
will raise exceptions.

Implement Symbol as Text in C-extension

---

amazon/ion/ioncmodule.c
amazon/ion/simple_types.py

I realized that when we were wrapping the std list in an IonPyList
we were copying it. Creating the IonPyList and filling it avoids
that and improves load performance, both time and memory usage.

Create and Build IonPyList instead of wrapping

---

amazon/ion/ioncmodule.c
amazon/ion/simple_types.py
tests/test_simpleion.py

Using a std Python dict is significantly faster. A dataset which is
streams of Structs (incredibly common) can expect gains of around 20%
for load times.

Implement STRUCT_AS_STD_DICT in C-extension load

---

amazon/ion/_ioncmodule.h
amazon/ion/ioncmodule.c
tests/test_simpleion.py

The previous STRUCT_AS_STD_DICT commit still builds a "hashmap of
lists" structure for "std" dicts, which was not intended. It was a
failure to get my WIP/POC code into that PR, which this change remedies.
I added a new test to actually verify the behavior. I kept but did
not add to the existing test_value_model_flags because that has a role
in covering the breadth of the IonPyValueFlags and I didn't want to
overcomplicate that for this Struct specific behavior.

Build Std Dict without Lists

---

amazon/ion/ioncmodule.c

N/A
This pull request optimizes the type checking logic while writing IonStruct by replacing `PyObject_IsInstance` with `PyObject_TypeCheck`. 
Originally, we use `PyObject_IsInstance` to determine if `obj` is an instance of `_ionpydict_cls` or any of its subclasses. In our use case, we are only interested in checking if `obj` is the type `_ionpydict_cls`, without the need to account for subclasses. This aligns with the behavior of` PyObject_TypeCheck`, which performs a direct comparison against the type of `obj` without considering the inheritance hierarchy, thus avoiding additional overhead.
Here are the benchmark results from benchmarking ion-python writing using service_log_legacy:
There is **_7.8%_** performance improvement from the …

Optimize type check while writing IonStruct.

---

amazon/ionbenchmark/benchmark_spec.py
amazon/ionbenchmark/ion_load_dump.py
tests/test_benchmark_spec.py

This change adds the ability to control the IonPyValueModel used in
benchmarking.

Plumb IonPyValueModel Flags from Benchmark Spec

---

amazon/ion/ioncmodule.c
amazon/ion/simple_types.py

This PR optimized the handling of `IonPyDict` objects. In the previous implementation, we converted the `PyObject` map into a `sequence` for iteration. The updated approach introduced in this PR separates the handling into two cases based on the type of the map object:
1. For Python dictionaries: When `map` is a standard Python dictionary, we iterate over it directly using `PyDict_Next`. 
2. For `IonPyDict` objects: In cases where map is an instance of IonPyDict, we now access its `_ _store` attribute. This attribute itself is a Python dictionary. By doing so, we can then use `PyDict_Next` to iterate over __store, similar to how we handle standard Python dictionaries.
This optimization eliminates the need to convert IonPyDict objects into …

Optimize ionc_write_struct

---

amazon/ion/ioncmodule.c
requirements.txt

This change uses the PyDateTime C API to access the Timestamp
attributes from the datetime super class. It improves Timestamp
serialization by about 10% for both Text and Binary. I expect the
improvement for basic datetimes to be higher but I haven't measured
it.
It should be compatible with future changes to the Timestamp types
so long as they still inherit from DateTime, which I think is a safe
assumption.

Use PyDateTime C API to Write Timestamps

---

.github/workflows/main.yml
.github/workflows/release.yml
requirements.txt

This PR adds support for wheels on Python 3.11 and MacOS-arm64.
In detail, this PR:
1. Adds wheels for Python 3.11.
2. Adds wheels for MacOS-arm64.
3. Drops support for wheels built with Python 3.6 to 3.8.
4. Updates required dependencies and build tools.
1. A successful wheel build workflow from my fork can be found at: https://github.com/cheqianh/ion-python/actions/runs/7880967937.
2. All tests have passed on GitHub Actions 

Updates the release workflow to support python 3.11 and MacOS arm64.

---

amazon/ion/core.py
amazon/ion/ioncmodule.c
tests/test_simpleion.py

The first commit refactors Timestamp construction, pulling the heavy-lifting validation and attribute setting logic out into
__init__ and leaving the bare minimum in __new__.
The second commit calls __new__ directly from ionc_read_timestamp and while avoiding building a dict of keyword
args.
A benchmark test I put together of all the timestamps from various "vectors" tests shows that this is about 2.7x faster
for reading timestamps. The impact to my "hkc" ion benchmark, which features a single Timestamp out of about 15 attributes per top-level-value is roughly a 25% improvement.

Optimize Timestamp Reads in ion-c extension

---

.github/dependabot.yml

This change adds a Dependabot[1] configuration to keep dependencies up-to-date. The routine will check files like https://github.com/amazon-ion/ion-python/blob/master/requirements.txt for any updates.
[1] https://docs.github.com/en/code-security/dependabot

Add dependabot configuration for keeping dependencies current

---

.github/dependabot.yml

**Issue #, if available:**
None.
**Description of changes:**
Updates the dependabot config so that dependabot won't throw a bunch of major version updates into it's regularly scheduled PRs.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

Set update types (minor, patch) in Dependabot config

---

amazon/ion/ioncmodule.c

*Issue #, if available:* #347
Prior to this PR the `ionc_read` function was decrementing the reference count of the `text_buffer_size_limit` argument resulting in a premature free, that could lead to improper memory access.
This PR removes that reference decrement.
---

Remove text_buffer_size_limit decref

---

amazon/ion/ioncmodule.c

Prior to this PR compilation of the C extension resulted in quite a bit of noise from compiler warnings and associated notes:
```
$ clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -Iamazon/ion/ion-c-build/include -Iamazon/ion/ion-c-build/include/ionc -Iamazon/ion/ion-c-build/include/decNumber -I/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c amazon/ion/ioncmodule.c -o build/temp.macosx-13.0-x86_64-cpython-312/amazon/ion/ioncmodule.o -std=c99 2>&1 | wc -l
82
```
The warnings consisted of the following:
```
amazon/ion/ioncmodule.c:183:10: warning: assigning to 'char *' from …
```

C Extension warning cleanup

---

amazon/ion/ioncmodule.c
tests/test_reader_base.py
tests/test_writer_base.py

*Issue #, if available:* #375
The ionc extension had a few uninitialized pointers defined in `ionc_write` that would get `Py_DECREF`'d when the arguments provided where invalid. This was found with the feature added with #372, when an extra parameter was passed to track whether to print trialing commas or not.
This PR initializes the values to NULL and changes the `Py_DECREF` to `Py_XDECREF` because `Py_DECREF` doesn't handle NULL values. Unit tests were also added to ensure we're returning an exception and not blowing up in these cases.
---

Fix invalid memory access in ionc_write

---

amazon/ion/simpleion.py
amazon/ion/writer_text.py
tests/test_simpleion.py
tests/test_writer_text.py

[Issue # 370](https://github.com/amazon-ion/ion-python/issues/370)
Add an optional boolean argument `trailing_commas` to the `dump` and `dumps` methods in `simpleion`. Default: False.
When `trailing_commas=True`, and when `indent` is not `None`, this causes `dump[s]` to include a comma on the last item in a container.
**Note:** Since the C module already **does not support pretty printing**, this flag does nothing when using the C module.

feat: Add `trailing_commas` to `dump`/`dumps`

---

.github/workflows/main.yml
.github/workflows/performance-regression.yml
requirements.txt
requirements_benchmark.txt

*Issue #, if available:* #377
This PR removes pypy from the performance regression workflows. It also removes the benchmark cli tests, and benchmark spec tests from the main build & tests workflows so that we can eliminate other format libraries that may not support pypy from our ci checks, in order to continue validating pypy correctness.
`requirements.txt` has been split and `requirements_benchmark.txt` has been populated with the dependencies needed only for benchmarking. When running the performance regression workflows, or local benchmarking efforts this new requirements file will need to be installed as well.
---

Remove pypy from benchmarking, and split requirements

---

README.md

No issue assigned, but problem identified during the course of working on PR #372 for Issue #370.
`setuptools.command.test` was removed in setuptools 72.x, so we can't use 72.x or newer without updating our ion-python's build/test setup. In addition, there was a breaking change, it seems, in 71.x, to `canonicalize_version()`.
By selecting setuptools **prior** to 71.0.0, the build and tests run successfully.
Errors encountered:
With setuptools 72.x:
```
...
import setuptools.command.test as orig
ModuleNotFoundError: No module named 'setuptools.command.test'
```
With setuptools 71.x:
```
...
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
```
By submitting this pull request, I confirm that my …

chore: Update README to reflect the need for an old enough setuptools

---

CHANGES.md
amazon/ion/__init__.py
setup.py

This PR updates the ion-python version to 0.13.0 in preparation for release.
---

Bumps version to 0.13.0

---

.github/workflows/release.yml

Missed the release workflow when updating unit testing to split benchmarks from functional tests. This PR adds the installation so that a bare `py.test` should test and validate all functionality.
---

Install benchmark requirements during release workflow

---

.github/workflows/release.yml

In a previous PR I added the installation of benchmark requirements to the release workflow prior to running tests. That PR introduced a syntax error which wasn't identified until the release workflow was evaluated post-merge. This PR reworks the dependency installation in order to fix that syntax error.
---

Fix Syntax Error in release.yml

---

.github/workflows/release.yml

This PR ignores benchmark related tests during the release workflow's test phase. When testing in pypy we are unable to run benchmark related tests, or the benchmark CLI, due to dependencies that do not support pypy. 
---

Remove benchmark related tests since they can't be run in pypy

---

.github/workflows/release.yml

With the release of 0.13.0 a few maintenance issues have popped up with the release workflow. The latest is a change to the MacOS runners which introduces [PEP-668](https://peps.python.org/pep-0668/), disallowing pip to be used directly on a system install. ([Example](https://github.com/amazon-ion/ion-python/actions/runs/11807251033/job/32893620133) failed run)
Most of our workflows use virtual environments, which satisfies PEP-668, however the release workflow does not use a virtual environment when building wheels with cibuildwheel.
This PR updates the release workflow to lean on the cibuildwheel GHA for building our wheels, rather than manually installing and running cibuildwheel. This simplifies the workflow, and allows the …

Fix release workflow, externally managed environment error

---

.github/workflows/release.yml

Prior to this PR the release workflow was relying on the `macos-latest` runner in order to build `x86_64` wheels. Since our 0.12.0 release, the `macos-latest` runner has become an alias for `macos-14`, which is an arm-based runner. This change causes our x86 wheel build to [fail](https://github.com/amazon-ion/ion-python/actions/runs/11827991785/job/32957301528#step:3:243).
Currently, `macos-13` is the only standard x86-based MacOS runner.
This PR changes our use of `macos-latest` to `macos-13` in order to regail x86 build capabilities. A future task should be taken up to use Arm-based runners to cross-compile x86. 
---

Address macos-latest update to arm-based MacOS 14

---

.github/workflows/release.yml

The recent update to upload-artifact and download-artifact GHAs changed the behavior around artifact naming. Previously multiple jobs could upload artifacts with the same name, and they would be merged together into a single artifact. With the newer versions jobs cannot upload artifacts with the same name, and must be given a unique name ([example](https://github.com/amazon-ion/ion-python/actions/runs/11829052156/job/32960265700#step:4:13) failure).
This PR adjusts the uploaded artifact's name to be unique per OS/Architecture build, and updates the `upload-wheels` job to handle the new names, and merge the individual files into the same directory.
---
By submitting this pull request, I confirm that my contribution is made under the …

Fix duplicate named archives in release workflow

---

.github/workflows/release.yml

This PR adds QEMU configuration back into the release workflow. The cibuildwheel action we rely on does not set qemu up itself, and will only use it if it exists prior to the action running.
I had some issues testing this out to confirm it works. On my setup QEMU keeps segfaulting while building ion-c at various places. I wasn't able to track the issue down to a root cause, and the crashes would occur in different places, which lead me to believe that something may have been off with the containers, or otherwise how `act` was setting up the environment.
Prior to moving to cibuildwheel's GHA, we manually ran cibuildwheel with QEMU configured this same way.
In addition to the QEMU configuration itself, I also added the linux specific …

Setup QEMU for Arm wheel builds

---

.github/workflows/release.yml

Prior to this PR the release workflow would build our wheels and upload them to S3, where a code pipeline would upload them to PyPI. Last year, PyPI removed the ability to upload wheels using user/pass for auth, and required either an API key, or configuring a Trusted Publisher.
This PR updates the release workflow to use PyPI's trusted publisher via Github. Rather than uploading the wheels to S3, and uploading them via the code pipeline with a secret key, we've configured our PyPI project to trust Github's OIDC provider. In our workflow we can request a token from Github (via the `pypa/gh-action-pypi-publish` action) which will be signed with Github's key, and verified by PyPI. The token contains claims containing the repo and …

Update release workflow to use PyPI's trusted publisher support.

---

.github/workflows/performance-regression.yml

The previous PR #379 updated half of the perf regression workflow to use the pyproject.toml for the PR-side of the benchmarking. This PR follows up to update the HEAD-side to use pyproject.toml now that the migration has been merged.
---

Follow-up PR to finish updating the performance regression workflow

---

.github/workflows/main.yml
.github/workflows/release.yml
CHANGES.md
pyproject.toml

This PR bumps the minimum supported version of python to 3.9, dropping 3.8 which has now been EOL'd for 6 months.
In addition, this PR:
* removes the 3.8 targets for both python and PyPy from our workflows
* fixes a typo in the changelog that suggested 3.8 had been dropped over a year ago
* adds 3.12 and 3.13 to the python versions tested in GHA CI/CD.
* merges the windows & linux/mac GHA test jobs back together now that 3.8 is dropped (#308)
Since python versions reach end of life every October, it would be nice to have our tests testing against the current supported versions, as well as the latest dev version (currently 3.14). I started looking into adding a GHA job to test the latest dev version and not fail the build if it fails, as …

Bump minimum python version to 3.9.

---

src-python/amazon/ion/writer_text.py

*Issue #, if available:* #410
*Description of changes:* Use a "with" statement to ensure that resources of the ByteIO object created in `_bytes_text` are released immediately after use. 

Release text writer byte buffer after use

---

.readthedocs.yaml
docs/conf.py
docs/requirements.txt

*Issue #, if available:* #209
In June 2021, the ion-python docs [started failing](https://app.readthedocs.org/projects/ion-python/builds/14027632/) due to pytest 6.2.4 not being found for python 2.7.
Issues with requirements while trying to run under python 2.7 continued until Oct 2023, when readthedocs started requiring projects to have a readthedocs configuration file in order to drive doc generation. Once this was enforced, the documentation build [started failing](https://app.readthedocs.org/projects/ion-python/builds/22147034/) for this reason.
This PR adds the `.readthedocs.yaml` configuration required by readthedocs.com, and updates the sphinx configuration in order to load the `amazon.ion` module after the migration to pyproject.
A new `requirements.txt` …

Add configuration for readthedocs, and tweak sphinx settings to work with recent pyproject migration.

---

tests/test_sliceable_buffer.py

Dependabot posted #416, which uncovered a weird import of pytest's `raises`. Looks like the API has changed with a recent release to no longer export raises there.
This PR adjusts the import to match the pytest API which should fix the dependabot PR.
---

Fix import of pytest's raises to newer(?) API.
